# Generated by Django 6.1.1 on 2026-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoAchado',
            fields=[
                ('id_objetoA', models.AutoField(primary_key=True, serialize=False)),
                ('nome_objeto_achado', models.CharField(max_length=255)),
                ('cor_achado', models.CharField(max_length=100)),
                ('nome_pessoa', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('contato', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'objetos_achados',
            },
        ),
        migrations.CreateModel(
            name='ObjetoPerdido',
            fields=[
                ('id_objeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_objeto', models.CharField(max_length=255)),
                ('cor', models.CharField(max_length=100)),
                ('data_perdido', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'objetos_perdidos',
            },
        ),
    ]
